//Line 4: SELECT 
//Example SELECT/PILIIN m.m.DATE_[YYYY-MM-DD][0] | SELECT/PILIIN 1.p.jo_number[1XXXXXX][1] | SELECT/PILIIN COUNT/BILANGIN 1.p.PROCESS_NAME [SMT.V/I-T][2]

//Line 4: FROM
//Example FROM/MULA SA TABLE (2 tables) master.mis_prod_plan_dl(1st table) at ang 1_smt.pcb (2nd table)

//Line 4: WHERE
//WHERE/KUNG SAAN ANG m.m.JOB_ORDER_NO[1XXXXXX] = (EQUAL O KAPAREHO NG) 1.p.jo_number [1XXXXXX] | [AND/AT TSAKA DAPAT] m.m.DATE_[YYYY-MM-DD] BETWEEN/PAGITAN NG $from% [variable from form] [YYYY-MM-DD] AND/AT NG $to% [variable from form] [YYYY-MM-DD] | AND/TSAKA DAPAT 1.p.jo_number [1XXXXXX] LIKE/MAY PAGKAKATULAD atlease '2%'

//Line 4: GROUP BY
//GROUP BY/MAGKAKASAMA SA KANIKANILANG DATE_ [YYYY-MM-DD]



//Line 22:
//DISPLAY SELECT/PILIIN COUNT/BILANGIN 1.p.PROCESS_NAME [SMT.V/I-T][2]